version: '3'
services:
  ap:
    image: sdelrio/rpi-hostap:latest
    privileged: true
    network_mode: "host"
    environment:
      - INTERFACE=wlan0
      - CHANNEL=6
      - SSID=runssid
      - AP_ADDR=192.168.254.1
      - SUBNET=192.168.254.0
      - WPA_PASSPHRASE=passw0rd
      - OUTGOINGS=eth0
